### ISSUE TITLE
Fixes I

### ISSUE THREAD

**Issue by zmicer-rasko** [Multyjog/sk.github.io#1]
1. Move all pics to folder `/img`
2. Use correct names for pictures: {page}_{block_if_exist}_{what_on_pic_or_number} like `feedback_1.png`
3. Move all styles into `site.css` put this file in root folder
4. Rename html files into:
- home.html
- catalog.html
- contact.html
- testimonials.html
- cart.html

Having spaces %20 in html page names does not look like a good practice.
![image](https://user-images.githubusercontent.com/75188408/100529350-b8150300-31f7-11eb-8d8c-6250ebae5a73.png)

5. Font size
![image](https://user-images.githubusercontent.com/75188408/100529195-db3eb300-31f5-11eb-99bf-702fe0b5cbe3.png)
![image](https://user-images.githubusercontent.com/75188408/100529198-f14c7380-31f5-11eb-9193-7220ff516f86.png)
6. Color 
![image](https://user-images.githubusercontent.com/75188408/100529205-fdd0cc00-31f5-11eb-9388-6803c5b0a470.png)
7. Shade 
![image](https://user-images.githubusercontent.com/75188408/100529211-04f7da00-31f6-11eb-9500-88e1eb76de7f.png)
8. Image margins and proportions 
![image](https://user-images.githubusercontent.com/75188408/100529215-1345f600-31f6-11eb-84d8-d3becc301d26.png)
9. Container width 
![image](https://user-images.githubusercontent.com/75188408/100529220-28bb2000-31f6-11eb-8e6b-363d32877494.png)
10. Header top margin
![image](https://user-images.githubusercontent.com/75188408/100529234-56a06480-31f6-11eb-9773-ed498ec51ca6.png)
11. Logo font-size
12. Logo pic->logo text margin
13. Let's make original pictures 200x200 as on moquap
![image](https://user-images.githubusercontent.com/75188408/100529330-78e6b200-31f7-11eb-9a7f-25cdd046013b.png)
14. What happens when you register on website tavuk-durum-lovers.com and uploading your avatar? Tell me if you got this. If not - ask. Next pic - is a clue :)
![image](https://user-images.githubusercontent.com/75188408/100529530-99177080-31f9-11eb-9beb-f7d4b4b6bebd.png)

UPD.
![image](https://user-images.githubusercontent.com/75188408/100529546-c95f0f00-31f9-11eb-8bd0-798e8e545754.png)
Some classes here are shouldn't be there. https://getbootstrap.com/docs/4.0/content/images/#responsive-images

**Comment by Multyjog** [comment]
пайшоў у дупу!
гэта занадта складана.
-----------------------------------------
Work in progress. Will be done

**Comment by zmicer-rasko** [comment]
@Multyjog 
+1 Move all pics to folder /img
+2 Use correct names for pictures: {page}{block_if_exist}{what_on_pic_or_number} like feedback_1.png
-3 Move all styles into site.css put this file in root folder
+4 Rename html files
+5 Font size
+6 Color
+7 Shade
+8 Image margins and proportions
+9 Container width
-10 Header top margin
+11 Logo font-size
+12 Logo pic->logo text margin
+13 Let's make original pictures 200x200 as on moquap
+14

UPDATE
15 Let's use montserrat fonts everywhere

**Comment by zmicer-rasko** [comment]
@Multyjog 
-10
-15
-16 home.html  a) Lines 5-11 formatting. b) "Viewport" and charset Triplication on each page. c) Check and clean <head> for all html pages.
![image](https://user-images.githubusercontent.com/75188408/101178270-d9dc1300-3659-11eb-8c4a-7d4fa87417a6.png)

-17 Do we need here `row` class (home.html)? 
![image](https://user-images.githubusercontent.com/75188408/101178398-02640d00-365a-11eb-91f4-0ce3f896e5c7.png)
-18 cart.html please remove copy-pasted classes 
![image](https://user-images.githubusercontent.com/75188408/101178801-79010a80-365a-11eb-8d80-2151ce0794b4.png)
